# CVFR Route Master — an Israel CVFR route-planning assistant
# for flight-simulator use.
# Copyright (C) 2026 Lev F.
#
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public
# License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# This program is intended for flight-simulator use only. The
# author disclaims any warranty of fitness for use in real-world
# aviation; any such use is entirely at the user's own risk and
# is not contemplated by this software. This program is not a
# substitute for official charts, NOTAMs, weather briefings, or
# any other official flight-planning material. Always cross-check
# against current AIP material before any simulated flight.

"""Tests for the cache-fingerprint restamping helper.

The helper (``scripts/_restamp_cache_fingerprints.py``) exists to fix
a build-pipeline bug specific to Linux releases built in WSL: the
dev cache JSONs in ``.cvfr_routemaster/`` store PDF mtimes with NTFS
sub-second precision (because they were generated by the app running
natively on Windows), but ``shutil.copy2`` reading those same PDFs
through WSL's ``/mnt/c/`` 9P bridge **floors mtimes to whole seconds**.
The shipped cache JSON's stored mtime and the shipped PDF's live
mtime end up disagreeing at the nanosecond level, every cache
fingerprint check rejects on first launch, and the user is hit with:

  * a re-OCR pass (needs Tesseract installed — not always present),
  * an altitude-arrow re-extraction (~30 s),
  * a map-PDF re-render to PNG (~30 s),
  * a modal "please re-calibrate the chart" dialog asking the user
    to click 8 anchor waypoints manually.

That last one is the showstopper that triggered the bug investigation:
on WSLg's Wayland compositor the dialog rendered offscreen and the
app appeared to hang at startup with only a tiny ``[WARN:COPY...]``
window slice in the taskbar.

The restamp helper rewrites every ``mtime_ns`` field in every cache
JSON to match the live PDF mtimes after ``_copy_charts`` and
``_copy_seed_cache``, so the fingerprints match by construction.

These tests cover:

  1. The happy path: a synthetic release tree with a cache JSON
     whose stored mtime is wrong gets it corrected, and the file is
     rewritten with the new mtime + preserved structure.
  2. Idempotency: running the helper twice in a row is a no-op the
     second time.
  3. Each of the five real cache file schemas — single-PDF
     (``waypoints_cache.json``, ``altitude_arrows_*.json``),
     dual-PDF flat (``map_images_meta.json``), and dual-PDF nested
     (``geo_calibration.json``) — all get their mtimes updated
     correctly.
  4. Edge cases: missing cache file (skipped, not failed), missing
     PDF the cache references (reported as ``missing_pdfs``, not
     crashed), absent ``mtime_ns`` field (skipped, not crashed),
     malformed top-level JSON (skipped).
  5. The CLI entrypoint (``python3 -m scripts._restamp_cache_fingerprints
     <dir>``): prints a summary, exits 0 on clean updates, exits 1
     when a referenced PDF is missing.
  6. Build-script integration: both ``scripts/build_release.py``
     and ``scripts/build_release_for_linux.py`` call the helper
     after ``_copy_seed_cache``.
  7. The regression that motivated this whole helper: the verbatim
     cache JSONs the broken WSL build shipped (sub-second mtimes
     in ``geo_calibration.json``) get fixed to match
     whole-second PDF mtimes when run through the helper.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest


# Match the production cache layout constants. Duplicated here rather
# than imported so a future move/rename of the production constants
# trips a clear test failure ("name not exported") rather than the
# tests silently picking up the new value.
RELEASE_PDF_SUBDIR = "map-pdfs"
RELEASE_CACHE_SUBDIR = ".cvfr_routemaster"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_release_tree(
    root: Path,
    pdfs: dict[str, int],
) -> Path:
    """Build a synthetic release tree at ``root``.

    Args:
        root: tmp directory that will become the release root.
        pdfs: mapping of PDF filename → mtime_ns to stamp on the
            created file. We use ``os.utime`` rather than relying on
            the filesystem's natural creation mtime so tests are
            deterministic across runs and machines.

    Returns:
        ``root`` (for convenience).
    """
    pdf_dir = root / RELEASE_PDF_SUBDIR
    cache_dir = root / RELEASE_CACHE_SUBDIR
    pdf_dir.mkdir(parents=True)
    cache_dir.mkdir(parents=True)
    for name, mtime_ns in pdfs.items():
        pdf_path = pdf_dir / name
        # Content size is fingerprinted too; we don't test mismatched
        # sizes (separate concern, not what this helper touches) but
        # we want a non-zero size so the fixtures look realistic.
        pdf_path.write_bytes(b"%PDF-1.4\nfake content for tests\n")
        import os

        os.utime(pdf_path, ns=(mtime_ns, mtime_ns))
    return root


def _write_cache(root: Path, name: str, data: dict) -> Path:
    """Write a JSON cache file under ``root/.cvfr_routemaster/``."""
    path = root / RELEASE_CACHE_SUBDIR / name
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return path


def _read_cache(root: Path, name: str) -> dict:
    return json.loads((root / RELEASE_CACHE_SUBDIR / name).read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Happy path
# ---------------------------------------------------------------------------


def test_restamp_corrects_stale_waypoints_mtime(tmp_path: Path) -> None:
    """The canonical drift case: cache JSON has sub-second mtime
    precision (Windows-native), PDF has whole-second mtime (WSL
    9P-floored). Helper rewrites the cache to match the PDF.
    """
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_BACK_PDF,
        restamp_cache_fingerprints,
    )

    live_pdf_mtime = 1777797103_000_000_000
    stale_cache_mtime = 1777797103_955_812_000

    root = _make_release_tree(tmp_path, {DEFAULT_BACK_PDF: live_pdf_mtime})
    _write_cache(
        root,
        "waypoints_cache.json",
        {
            "back_pdf": {
                "path": f"/release-linux/map-pdfs/{DEFAULT_BACK_PDF}",
                "mtime_ns": stale_cache_mtime,
                "size": 202103,
            },
            "records": [],
        },
    )

    report = restamp_cache_fingerprints(root)

    assert report.updates == {
        "waypoints_cache.json": [
            ("back_pdf", stale_cache_mtime, live_pdf_mtime)
        ]
    }
    # Other caches not present in this fixture ⇒ legitimately skipped.
    # The check that matters is "nothing crashed and nothing was
    # flagged as a build error".
    assert report.missing_pdfs == []

    cached = _read_cache(root, "waypoints_cache.json")
    assert cached["back_pdf"]["mtime_ns"] == live_pdf_mtime
    # The size field is untouched on purpose — restamping mtime only.
    assert cached["back_pdf"]["size"] == 202103
    # Unrelated keys preserved.
    assert cached["records"] == []


def test_restamp_is_idempotent(tmp_path: Path) -> None:
    """Second call after a successful first call reports zero updates."""
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_BACK_PDF,
        restamp_cache_fingerprints,
    )

    live_pdf_mtime = 1777797103_000_000_000
    root = _make_release_tree(tmp_path, {DEFAULT_BACK_PDF: live_pdf_mtime})
    _write_cache(
        root,
        "waypoints_cache.json",
        {
            "back_pdf": {
                "path": "ignored",
                "mtime_ns": 999,
                "size": 1,
            },
        },
    )

    first = restamp_cache_fingerprints(root)
    assert first.total_fields_updated() == 1

    second = restamp_cache_fingerprints(root)
    assert second.total_fields_updated() == 0
    assert second.updates == {}


def test_restamp_geo_calibration_dual_nested_pdf(tmp_path: Path) -> None:
    """``geo_calibration.json`` has two PDFs nested under
    ``north.pdf`` and ``south.pdf``. This is the schema that
    motivated the bug — verbatim from the broken WSL build.
    """
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_NORTH_PDF,
        DEFAULT_SOUTH_PDF,
        restamp_cache_fingerprints,
    )

    north_live = 1777797121_000_000_000
    south_live = 1777797137_000_000_000
    north_stale = 1777797121_332_421_700
    south_stale = 1777797137_316_700_700

    root = _make_release_tree(
        tmp_path,
        {DEFAULT_NORTH_PDF: north_live, DEFAULT_SOUTH_PDF: south_live},
    )
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "version": 1,
            "north": {
                "pdf": {
                    "path": f"<repo-root>\\\\{DEFAULT_NORTH_PDF}",
                    "mtime_ns": north_stale,
                    "size": 7910912,
                },
                "points": [{"code": "HOTRM"}],
                "map_layout": {"x": 0.0, "y": 0.0, "scale": 1.0},
            },
            "south": {
                "pdf": {
                    "path": f"<repo-root>\\\\{DEFAULT_SOUTH_PDF}",
                    "mtime_ns": south_stale,
                    "size": 8697353,
                },
                "points": [{"code": "OMER"}],
                "map_layout": {"x": 100.0, "y": 200.0, "scale": 1.0},
            },
        },
    )

    report = restamp_cache_fingerprints(root)

    updates = report.updates["geo_calibration.json"]
    assert sorted(updates) == sorted(
        [
            ("north.pdf", north_stale, north_live),
            ("south.pdf", south_stale, south_live),
        ]
    )

    cached = _read_cache(root, "geo_calibration.json")
    assert cached["north"]["pdf"]["mtime_ns"] == north_live
    assert cached["south"]["pdf"]["mtime_ns"] == south_live
    # Anchor data and map layout (the actually-valuable calibration
    # state) must be preserved bit-for-bit through the restamp.
    assert cached["north"]["points"] == [{"code": "HOTRM"}]
    assert cached["south"]["points"] == [{"code": "OMER"}]
    assert cached["south"]["map_layout"] == {"x": 100.0, "y": 200.0, "scale": 1.0}


def test_restamp_map_images_meta_dual_flat_pdf(tmp_path: Path) -> None:
    """``map_images_meta.json`` has two PDFs at the top level
    (``north_pdf`` and ``south_pdf``)."""
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_NORTH_PDF,
        DEFAULT_SOUTH_PDF,
        restamp_cache_fingerprints,
    )

    north_live = 1777797121_000_000_000
    south_live = 1777797137_000_000_000

    root = _make_release_tree(
        tmp_path,
        {DEFAULT_NORTH_PDF: north_live, DEFAULT_SOUTH_PDF: south_live},
    )
    _write_cache(
        root,
        "map_images_meta.json",
        {
            "cache_format_version": 2,
            "north_pdf": {
                "path": "ignored",
                "mtime_ns": 111,
                "size": 7910912,
            },
            "south_pdf": {
                "path": "ignored",
                "mtime_ns": 222,
                "size": 8697353,
            },
        },
    )

    report = restamp_cache_fingerprints(root)
    updates = sorted(report.updates["map_images_meta.json"])
    assert updates == [
        ("north_pdf", 111, north_live),
        ("south_pdf", 222, south_live),
    ]


def test_restamp_altitude_arrows_each_sheet(tmp_path: Path) -> None:
    """The two altitude-arrow caches (north + south) each fingerprint
    their own sheet's PDF."""
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_NORTH_PDF,
        DEFAULT_SOUTH_PDF,
        restamp_cache_fingerprints,
    )

    north_live = 1777797121_000_000_000
    south_live = 1777797137_000_000_000

    root = _make_release_tree(
        tmp_path,
        {DEFAULT_NORTH_PDF: north_live, DEFAULT_SOUTH_PDF: south_live},
    )
    _write_cache(
        root,
        "altitude_arrows_north.json",
        {"pdf": {"path": "x", "mtime_ns": 1, "size": 7910912}, "arrows": []},
    )
    _write_cache(
        root,
        "altitude_arrows_south.json",
        {"pdf": {"path": "x", "mtime_ns": 2, "size": 8697353}, "arrows": []},
    )

    report = restamp_cache_fingerprints(root)
    assert report.updates["altitude_arrows_north.json"] == [
        ("pdf", 1, north_live)
    ]
    assert report.updates["altitude_arrows_south.json"] == [
        ("pdf", 2, south_live)
    ]


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


def test_missing_cache_file_is_skipped_not_failed(tmp_path: Path) -> None:
    """A cache file the binding expects but the dev environment
    didn't generate (e.g. user never calibrated south) is skipped
    silently. Optional caches must not block the build."""
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_BACK_PDF,
        DEFAULT_NORTH_PDF,
        DEFAULT_SOUTH_PDF,
        restamp_cache_fingerprints,
    )

    root = _make_release_tree(
        tmp_path,
        {
            DEFAULT_BACK_PDF: 1_000_000_000,
            DEFAULT_NORTH_PDF: 2_000_000_000,
            DEFAULT_SOUTH_PDF: 3_000_000_000,
        },
    )
    # Only one cache file present out of the five the helper knows about.
    _write_cache(
        root,
        "waypoints_cache.json",
        {"back_pdf": {"path": "x", "mtime_ns": 999, "size": 1}},
    )

    report = restamp_cache_fingerprints(root)
    assert "waypoints_cache.json" in report.updates
    # The four missing caches should all be listed as skipped.
    assert sorted(report.skipped) == sorted(
        [
            "geo_calibration.json",
            "altitude_arrows_north.json",
            "altitude_arrows_south.json",
            "map_images_meta.json",
        ]
    )
    assert report.missing_pdfs == []


def test_missing_pdf_is_reported_not_crashed(tmp_path: Path) -> None:
    """A cache JSON references a PDF that isn't in ``map-pdfs/``.
    That's a build-pipeline ordering bug, so the helper records the
    missing PDF in ``missing_pdfs`` and the CLI exits 1 — but
    in-process callers (the build scripts) get to decide how to
    react. The cache file itself must NOT be partially rewritten."""
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_BACK_PDF,
        restamp_cache_fingerprints,
    )

    root = _make_release_tree(tmp_path, {})  # No PDFs at all.
    _write_cache(
        root,
        "waypoints_cache.json",
        {"back_pdf": {"path": "x", "mtime_ns": 999, "size": 1}},
    )

    report = restamp_cache_fingerprints(root)
    assert report.missing_pdfs == [DEFAULT_BACK_PDF]
    # Nothing got updated because the PDF wasn't there to read mtime from.
    assert "waypoints_cache.json" not in report.updates
    # And the cache file was NOT rewritten with garbage.
    assert _read_cache(root, "waypoints_cache.json")["back_pdf"]["mtime_ns"] == 999


def test_cache_without_mtime_ns_field_is_skipped(tmp_path: Path) -> None:
    """A cache JSON where the expected ``pdf`` sub-dict exists but
    has no ``mtime_ns`` key (e.g. an older format version) is
    skipped without crashing. We don't want to invent a value."""
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_BACK_PDF,
        restamp_cache_fingerprints,
    )

    root = _make_release_tree(
        tmp_path, {DEFAULT_BACK_PDF: 1_000_000_000}
    )
    _write_cache(
        root,
        "waypoints_cache.json",
        {"back_pdf": {"path": "x", "size": 1}},  # no mtime_ns
    )

    report = restamp_cache_fingerprints(root)
    assert "waypoints_cache.json" not in report.updates
    # Original content preserved verbatim.
    assert "mtime_ns" not in _read_cache(root, "waypoints_cache.json")["back_pdf"]


def test_cache_with_non_dict_top_level_is_skipped(tmp_path: Path) -> None:
    """A cache JSON that's a list (or any non-dict) at the top level
    is skipped. Shouldn't happen in practice, but the helper must
    never crash on a corrupted/empty cache file."""
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_BACK_PDF,
        restamp_cache_fingerprints,
    )

    root = _make_release_tree(
        tmp_path, {DEFAULT_BACK_PDF: 1_000_000_000}
    )
    # Top-level is a list, not a dict.
    (root / RELEASE_CACHE_SUBDIR / "waypoints_cache.json").write_text(
        "[1, 2, 3]\n", encoding="utf-8"
    )

    report = restamp_cache_fingerprints(root)
    assert "waypoints_cache.json" in report.skipped


def test_unknown_json_path_segment_is_skipped(tmp_path: Path) -> None:
    """If a cache JSON's schema has shifted (e.g. ``back_pdf`` moved
    under a new wrapper key), the binding's path won't resolve.
    Helper must skip that field rather than crash, so a future schema
    bump doesn't block the build until both sides are updated."""
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_BACK_PDF,
        restamp_cache_fingerprints,
    )

    root = _make_release_tree(
        tmp_path, {DEFAULT_BACK_PDF: 1_000_000_000}
    )
    _write_cache(
        root,
        "waypoints_cache.json",
        # Schema mutation: ``back_pdf`` is now under ``v2.pdf_meta``.
        # Helper's binding still looks for ``back_pdf`` at top level.
        {"v2": {"pdf_meta": {"mtime_ns": 999}}},
    )

    report = restamp_cache_fingerprints(root)
    assert "waypoints_cache.json" not in report.updates
    # Nothing rewritten.
    assert _read_cache(root, "waypoints_cache.json") == {
        "v2": {"pdf_meta": {"mtime_ns": 999}}
    }


# ---------------------------------------------------------------------------
# Top-level / structural error handling
# ---------------------------------------------------------------------------


def test_missing_release_dir_raises(tmp_path: Path) -> None:
    """Pointing at a nonexistent release dir is a build-pipeline
    ordering bug — must raise FileNotFoundError, not silently no-op."""
    from scripts._restamp_cache_fingerprints import restamp_cache_fingerprints

    with pytest.raises(FileNotFoundError, match="Release directory"):
        restamp_cache_fingerprints(tmp_path / "does-not-exist")


def test_missing_pdf_subdir_raises(tmp_path: Path) -> None:
    """``map-pdfs/`` absent ⇒ ``_copy_charts`` didn't run.
    Calling the restamp helper anyway is a build-ordering bug."""
    from scripts._restamp_cache_fingerprints import restamp_cache_fingerprints

    (tmp_path / RELEASE_CACHE_SUBDIR).mkdir()
    with pytest.raises(FileNotFoundError, match="PDF subdirectory"):
        restamp_cache_fingerprints(tmp_path)


def test_missing_cache_subdir_raises(tmp_path: Path) -> None:
    """``.cvfr_routemaster/`` absent ⇒ ``_copy_seed_cache`` didn't run.
    Same ordering bug."""
    from scripts._restamp_cache_fingerprints import restamp_cache_fingerprints

    (tmp_path / RELEASE_PDF_SUBDIR).mkdir()
    with pytest.raises(FileNotFoundError, match="Cache subdirectory"):
        restamp_cache_fingerprints(tmp_path)


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------


def test_cli_exits_zero_on_clean_restamp(tmp_path: Path) -> None:
    """``python3 -m scripts._restamp_cache_fingerprints <dir>`` ⇒ rc 0
    when everything resolves and at least one mtime was updated."""
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_BACK_PDF,
    )

    root = _make_release_tree(tmp_path, {DEFAULT_BACK_PDF: 1_000_000_000})
    _write_cache(
        root,
        "waypoints_cache.json",
        {"back_pdf": {"path": "x", "mtime_ns": 999, "size": 1}},
    )

    repo_root = Path(__file__).resolve().parents[1]
    result = subprocess.run(
        [sys.executable, "-m", "scripts._restamp_cache_fingerprints", str(root)],
        cwd=repo_root,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert "Updated waypoints_cache.json" in result.stdout
    assert "back_pdf.mtime_ns" in result.stdout


def test_cli_exits_zero_when_already_in_sync(tmp_path: Path) -> None:
    """No updates needed AND no skipped/missing — clean exit, idle
    message. This is the steady-state CI invocation after a build
    that already had the restamp baked in."""
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_BACK_PDF,
        DEFAULT_NORTH_PDF,
        DEFAULT_SOUTH_PDF,
    )

    mtimes = {
        DEFAULT_BACK_PDF: 1_000_000_000,
        DEFAULT_NORTH_PDF: 2_000_000_000,
        DEFAULT_SOUTH_PDF: 3_000_000_000,
    }
    root = _make_release_tree(tmp_path, mtimes)
    # All five caches present with mtimes already matching.
    _write_cache(
        root,
        "waypoints_cache.json",
        {"back_pdf": {"path": "x", "mtime_ns": mtimes[DEFAULT_BACK_PDF], "size": 1}},
    )
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "north": {"pdf": {"path": "x", "mtime_ns": mtimes[DEFAULT_NORTH_PDF], "size": 1}},
            "south": {"pdf": {"path": "x", "mtime_ns": mtimes[DEFAULT_SOUTH_PDF], "size": 1}},
        },
    )
    _write_cache(
        root,
        "altitude_arrows_north.json",
        {"pdf": {"path": "x", "mtime_ns": mtimes[DEFAULT_NORTH_PDF], "size": 1}},
    )
    _write_cache(
        root,
        "altitude_arrows_south.json",
        {"pdf": {"path": "x", "mtime_ns": mtimes[DEFAULT_SOUTH_PDF], "size": 1}},
    )
    _write_cache(
        root,
        "map_images_meta.json",
        {
            "north_pdf": {"path": "x", "mtime_ns": mtimes[DEFAULT_NORTH_PDF], "size": 1},
            "south_pdf": {"path": "x", "mtime_ns": mtimes[DEFAULT_SOUTH_PDF], "size": 1},
        },
    )

    repo_root = Path(__file__).resolve().parents[1]
    result = subprocess.run(
        [sys.executable, "-m", "scripts._restamp_cache_fingerprints", str(root)],
        cwd=repo_root,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert "already match" in result.stdout


def test_cli_exits_one_on_missing_pdf(tmp_path: Path) -> None:
    """A cache JSON references a PDF that isn't present ⇒ CLI rc 1
    (used by CI to fail loudly on a half-built release)."""
    from scripts._restamp_cache_fingerprints import DEFAULT_BACK_PDF

    root = _make_release_tree(tmp_path, {})  # No PDFs.
    _write_cache(
        root,
        "waypoints_cache.json",
        {"back_pdf": {"path": "x", "mtime_ns": 999, "size": 1}},
    )

    repo_root = Path(__file__).resolve().parents[1]
    result = subprocess.run(
        [sys.executable, "-m", "scripts._restamp_cache_fingerprints", str(root)],
        cwd=repo_root,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 1
    assert DEFAULT_BACK_PDF in result.stderr


def test_cli_exits_two_on_missing_release_dir(tmp_path: Path) -> None:
    """Bad CLI argument (nonexistent release dir) ⇒ rc 2 with a
    message naming the missing path. Distinct from the rc 1 path
    so CI can tell ordering bugs apart from PDF-missing bugs."""
    repo_root = Path(__file__).resolve().parents[1]
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "scripts._restamp_cache_fingerprints",
            str(tmp_path / "missing"),
        ],
        cwd=repo_root,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 2
    assert "Release directory" in result.stderr


# ---------------------------------------------------------------------------
# Build-script integration
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "build_script,subdir_name",
    [
        ("scripts/build_release.py", "release"),
        ("scripts/build_release_for_linux.py", "release-linux"),
    ],
)
def test_build_script_calls_derived_files_after_seed_cache(
    build_script: str,
    subdir_name: str,  # noqa: ARG001 — kept for parametrize symmetry
) -> None:
    """Both build scripts must invoke ``_write_shipped_derived_files``
    AFTER ``_copy_seed_cache``.

    v3.3+ replaced the old ``_restamp_cache_fingerprints`` build
    step (which depended on shipped PDFs being in place — gone
    now that charts are downloaded at runtime) with
    ``_write_shipped_derived_files``, which bakes:

    * ``chart_sources.json`` (the three default CAAI URLs),
    * ``map_layout.json`` (from the calibration), and
    * ``font_settings.json`` (from the dev's QSettings).

    ``write_shipped_map_layout`` and the path-sanitiser both read
    the shipped cache JSONs, so ``_copy_seed_cache`` must run
    first. We pin the call ordering by parsing the build script
    source and confirming the function names appear in the
    expected sequence.
    """
    repo_root = Path(__file__).resolve().parents[1]
    src = (repo_root / build_script).read_text(encoding="utf-8")

    def _find_call(needle: str) -> int:
        marker = f"    {needle}()"
        pos = src.find(marker)
        assert pos != -1, f"{build_script} does not call {needle}() in main()"
        return pos

    seed_pos = _find_call("_copy_seed_cache")
    derived_pos = _find_call("_write_shipped_derived_files")
    sanitize_pos = _find_call("_sanitize_shipped_cache_paths")

    assert seed_pos < derived_pos, (
        f"{build_script}: _write_shipped_derived_files must run AFTER "
        "_copy_seed_cache (it reads the shipped cache JSONs)"
    )
    assert derived_pos < sanitize_pos, (
        f"{build_script}: _sanitize_shipped_cache_paths must run AFTER "
        "_write_shipped_derived_files (the sanitiser is the last write "
        "pass over the shipped JSONs; running it earlier would let dev "
        "paths leak through the later derived-file writes)"
    )

    # Belt-and-braces: the removed v3.2 build steps must NOT
    # reappear via a copy-paste mistake. ``_copy_charts()`` and
    # ``_restamp_cache_fingerprints()`` belong to the pre-v3.3
    # era when PDFs were shipped — they have no place in the
    # new pipeline and silently re-adding them would cause
    # subtle regressions (an empty release/map-pdfs/ folder
    # appearing, or a restamp pass that fails on the now-absent
    # PDFs).
    for forbidden in ("_copy_charts()", "_restamp_cache_fingerprints()"):
        # Match only as a bare call inside main() (4-space indent),
        # not as a docstring mention.
        forbidden_marker = f"    {forbidden}"
        assert forbidden_marker not in src, (
            f"{build_script}: v3.3+ must NOT call {forbidden} — the "
            f"chart-fetch refactor removed that step. Found a bare "
            f"call at indent-4 in main()."
        )


# ---------------------------------------------------------------------------
# Shipped map_layout.json generation
# ---------------------------------------------------------------------------
#
# These tests cover the fix for the second-order startup bug found
# while debugging release v2: ``geo_calibration.json`` records the
# on-screen sheet position the dev used when capturing the
# calibration, but the **actual** current sheet position on first
# launch is loaded from QSettings (per-user, doesn't ship with the
# release). On a fresh QSettings, the sheets land at the hard-coded
# vertical-stack default, ``map_layout_matches`` rejects the
# calibration as "different layout", and the modal "please
# re-calibrate" dialog fires.
#
# Earlier iterations of this code tried to *normalise the
# calibration's map_layout to the release default* — destroying the
# dev's intent. The right fix, captured by these tests, is the
# opposite: ship a release-side ``map_layout.json`` that
# ``load_map_layout`` consults as a second-priority fallback after
# QSettings, so first launch on any machine restores **the dev's**
# calibrated layout. The user's own arrangements on the release
# machine still win once they make them (saved to QSettings).


def _write_meta_with_north_height(root: Path, north_height: int) -> None:
    """Helper: write a minimal ``map_images_meta.json`` with just the
    ``north_crop.cropped_h`` field the layout-restamp needs. Other
    fields are placeholders since the function doesn't read them."""
    _write_cache(
        root,
        "map_images_meta.json",
        {
            "cache_format_version": 2,
            "north_pdf": {"path": "x", "mtime_ns": 1, "size": 1},
            "south_pdf": {"path": "x", "mtime_ns": 1, "size": 1},
            "north_crop": {
                "offset_x": 0,
                "offset_y": 0,
                "source_w": 0,
                "source_h": 0,
                "cropped_w": 0,
                "cropped_h": north_height,
            },
            "south_crop": {
                "offset_x": 0,
                "offset_y": 0,
                "source_w": 0,
                "source_h": 0,
                "cropped_w": 0,
                "cropped_h": 0,
            },
        },
    )


def test_shipped_map_layout_derives_from_both_calibrated_sheets(tmp_path: Path) -> None:
    """The canonical case: both sheets have ``map_layout`` blocks in
    ``geo_calibration.json`` (the dev calibrated both), the shipped
    layout file mirrors them verbatim. This is the path the
    production build takes for a fully-calibrated release."""
    from scripts._restamp_cache_fingerprints import (
        SHIPPED_MAP_LAYOUT_FILE,
        write_shipped_map_layout,
    )

    root = _make_release_tree(tmp_path, {})
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "version": 1,
            "north": {
                "pdf": {"path": "x", "mtime_ns": 1, "size": 1},
                "points": [{"code": "HOTRM"}],
                "map_layout": {"x": 0.0, "y": 0.0, "scale": 1.0},
            },
            "south": {
                "pdf": {"path": "x", "mtime_ns": 1, "size": 1},
                "points": [{"code": "OMER"}],
                "map_layout": {
                    "x": -84.09126303968651,
                    "y": 9268.322841823778,
                    "scale": 1.0,
                },
            },
        },
    )

    report = write_shipped_map_layout(root)

    assert report.reason is None
    assert report.written is not None
    assert report.written.name == SHIPPED_MAP_LAYOUT_FILE
    assert report.layout == {
        "north_x": 0.0,
        "north_y": 0.0,
        "north_scale": 1.0,
        "south_x": -84.09126303968651,
        "south_y": 9268.322841823778,
        "south_scale": 1.0,
        "selected": "south",
    }

    # Round-trip: file content matches the in-memory report.
    on_disk = _read_cache(root, SHIPPED_MAP_LAYOUT_FILE)
    assert on_disk == report.layout


def test_shipped_map_layout_idempotent(tmp_path: Path) -> None:
    """Calling twice produces the same file. The helper rewrites the
    same content; we don't have a "no changes" short-circuit because
    the cost is tiny (a sub-1-KiB JSON write) and the simpler code
    path is worth the trade."""
    from scripts._restamp_cache_fingerprints import (
        write_shipped_map_layout,
    )

    root = _make_release_tree(tmp_path, {})
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "north": {"map_layout": {"x": 1.0, "y": 2.0, "scale": 1.0}},
            "south": {"map_layout": {"x": 3.0, "y": 4.0, "scale": 1.0}},
        },
    )

    first = write_shipped_map_layout(root)
    second = write_shipped_map_layout(root)
    assert first.layout == second.layout


def test_shipped_map_layout_uses_default_for_uncalibrated_sheet(
    tmp_path: Path,
) -> None:
    """Only south was calibrated. The shipped file uses the in-app
    default for north (vertical-stack: north at ``(0, 0, 1.0)``).
    This means a release with only one sheet calibrated still ships
    a complete layout file that load_map_layout can apply
    unconditionally."""
    from scripts._restamp_cache_fingerprints import (
        write_shipped_map_layout,
    )

    root = _make_release_tree(tmp_path, {})
    # No "north" block at all — only south is calibrated.
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "south": {
                "map_layout": {"x": 100.0, "y": 200.0, "scale": 1.0},
            },
        },
    )
    _write_meta_with_north_height(root, 10536)  # not strictly needed when north has a layout, but symmetry

    report = write_shipped_map_layout(root)

    assert report.reason is None
    assert report.layout is not None
    # North filled in with default placement; south taken from the
    # calibration.
    assert report.layout["north_x"] == 0.0
    assert report.layout["north_y"] == 0.0
    assert report.layout["north_scale"] == 1.0
    assert report.layout["south_x"] == 100.0
    assert report.layout["south_y"] == 200.0


def test_shipped_map_layout_uses_default_for_uncalibrated_south(
    tmp_path: Path,
) -> None:
    """Symmetric case: only north was calibrated. The default
    south_y must be computed from the north pixmap height in
    map_images_meta.json (so the south sheet appears stacked below
    north — the in-app default)."""
    from scripts._restamp_cache_fingerprints import (
        write_shipped_map_layout,
    )

    root = _make_release_tree(tmp_path, {})
    _write_meta_with_north_height(root, 10536)
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "north": {
                "map_layout": {"x": 50.0, "y": 60.0, "scale": 1.0},
            },
        },
    )

    report = write_shipped_map_layout(root)

    assert report.reason is None
    assert report.layout is not None
    assert report.layout["north_x"] == 50.0
    assert report.layout["north_y"] == 60.0
    assert report.layout["south_x"] == 0.0
    assert report.layout["south_y"] == 10536.0


def test_shipped_map_layout_missing_calibration_file_no_op(tmp_path: Path) -> None:
    """No ``geo_calibration.json`` ⇒ nothing to derive. Helper
    reports ``file_absent`` and the build script treats it as a
    benign "no calibration to ship; user will calibrate on first
    run" event. No file is written."""
    from scripts._restamp_cache_fingerprints import (
        SHIPPED_MAP_LAYOUT_FILE,
        write_shipped_map_layout,
    )

    root = _make_release_tree(tmp_path, {})
    # No geo_calibration.json written.

    report = write_shipped_map_layout(root)
    assert report.written is None
    assert report.layout is None
    assert report.reason == "file_absent"
    assert not (root / RELEASE_CACHE_SUBDIR / SHIPPED_MAP_LAYOUT_FILE).exists()


def test_shipped_map_layout_no_usable_layouts(tmp_path: Path) -> None:
    """``geo_calibration.json`` exists but has no ``map_layout``
    blocks (e.g. older format, or partial/corrupt content). Helper
    reports ``no_layouts`` and doesn't write a stub — the in-app
    defaults will apply on first launch."""
    from scripts._restamp_cache_fingerprints import (
        SHIPPED_MAP_LAYOUT_FILE,
        write_shipped_map_layout,
    )

    root = _make_release_tree(tmp_path, {})
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "north": {"points": []},  # no map_layout
            "south": {"points": []},
        },
    )

    report = write_shipped_map_layout(root)
    assert report.written is None
    assert report.reason == "no_layouts"
    assert not (root / RELEASE_CACHE_SUBDIR / SHIPPED_MAP_LAYOUT_FILE).exists()


def test_shipped_map_layout_uncalibrated_south_needs_meta(tmp_path: Path) -> None:
    """North calibrated but south not, AND ``map_images_meta.json``
    missing ⇒ we can't compute the default south_y. Helper reports
    ``meta_missing`` so the build script fails loudly. Without
    ``meta_missing`` we'd silently ship a layout file with south at
    ``(0, 0)`` (overlapping north entirely) which would visually
    look catastrophically broken on first launch."""
    from scripts._restamp_cache_fingerprints import (
        write_shipped_map_layout,
    )

    root = _make_release_tree(tmp_path, {})
    # No map_images_meta.json.
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "north": {"map_layout": {"x": 0.0, "y": 0.0, "scale": 1.0}},
        },
    )

    report = write_shipped_map_layout(root)
    assert report.written is None
    assert report.reason == "meta_missing"


def test_shipped_map_layout_both_calibrated_no_meta_needed(tmp_path: Path) -> None:
    """When both sheets have their own map_layout, the helper must
    NOT require ``map_images_meta.json`` — the meta is only needed
    to compute a *default* south_y, and there's no default if south
    is already calibrated. This is the common production case."""
    from scripts._restamp_cache_fingerprints import (
        write_shipped_map_layout,
    )

    root = _make_release_tree(tmp_path, {})
    # No map_images_meta.json written — must still succeed.
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "north": {"map_layout": {"x": 0.0, "y": 0.0, "scale": 1.0}},
            "south": {"map_layout": {"x": 1.0, "y": 2.0, "scale": 1.0}},
        },
    )

    report = write_shipped_map_layout(root)
    assert report.reason is None
    assert report.layout == {
        "north_x": 0.0,
        "north_y": 0.0,
        "north_scale": 1.0,
        "south_x": 1.0,
        "south_y": 2.0,
        "south_scale": 1.0,
        "selected": "south",
    }


@pytest.fixture
def _isolated_qsettings(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """Redirect :func:`cvfr_routemaster.settings_store._settings` to
    a per-test INI file so the round-trip tests don't read or
    write the dev machine's real Windows registry / Linux conf dir.

    Same pattern as the ``isolated_settings`` fixture in
    ``test_window_layout_persistence.py`` — using ``IniFormat``
    keeps everything inside ``tmp_path``, which pytest auto-cleans.
    """
    from PySide6.QtCore import QSettings

    from cvfr_routemaster import settings_store

    ini_path = tmp_path / "qsettings.ini"

    def _factory() -> QSettings:
        return QSettings(str(ini_path), QSettings.Format.IniFormat)

    monkeypatch.setattr(settings_store, "_settings", _factory)
    return ini_path


def test_shipped_map_layout_round_trips_through_load_map_layout(
    tmp_path: Path, _isolated_qsettings: Path
) -> None:
    """End-to-end: the file the build helper writes is read back
    correctly by :func:`cvfr_routemaster.settings_store.load_map_layout`
    (the in-app loader). This is the contract that makes the whole
    mechanism work — if the helper writes a shape the loader doesn't
    understand, the release ships a layout that's silently ignored
    on first launch and the user gets the modal recalibration prompt
    anyway. We test with an empty (isolated) QSettings so the
    shipped-file fallback rung is exercised; the QSettings-wins
    case has its own dedicated test below.
    """
    from cvfr_routemaster.settings_store import load_map_layout
    from scripts._restamp_cache_fingerprints import write_shipped_map_layout

    root = _make_release_tree(tmp_path, {})
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "north": {"map_layout": {"x": 0.0, "y": 0.0, "scale": 1.0}},
            "south": {
                "map_layout": {
                    "x": -84.09126303968651,
                    "y": 9268.322841823778,
                    "scale": 1.0,
                }
            },
        },
    )
    write_shipped_map_layout(root)

    loaded = load_map_layout(root)
    assert loaded is not None
    assert loaded["north_x"] == 0.0
    assert loaded["north_y"] == 0.0
    assert loaded["north_scale"] == 1.0
    assert loaded["south_x"] == -84.09126303968651
    assert loaded["south_y"] == 9268.322841823778
    assert loaded["south_scale"] == 1.0
    assert loaded["selected"] == "south"


def test_load_map_layout_qsettings_wins_over_shipped_file(
    tmp_path: Path, _isolated_qsettings: Path
) -> None:
    """User customisation precedence: once the user moves a sheet
    on the release machine, their layout is saved to QSettings via
    :func:`save_map_layout`. From that point on, QSettings is the
    source of truth — the shipped-file fallback must NOT clobber
    the user's choice.

    Without this priority the user would have to dismiss the
    shipped layout every launch ("why did the sheets move back?").
    """
    from cvfr_routemaster.settings_store import (
        load_map_layout,
        save_map_layout,
    )
    from scripts._restamp_cache_fingerprints import write_shipped_map_layout

    root = _make_release_tree(tmp_path, {})
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "north": {"map_layout": {"x": 0.0, "y": 0.0, "scale": 1.0}},
            "south": {"map_layout": {"x": 999.0, "y": 999.0, "scale": 1.0}},
        },
    )
    write_shipped_map_layout(root)

    # User makes their own arrangement.
    save_map_layout(
        north_x=11.0,
        north_y=22.0,
        north_scale=1.0,
        south_x=33.0,
        south_y=44.0,
        south_scale=1.0,
        selected="north",
    )

    loaded = load_map_layout(root)
    assert loaded is not None
    # User's saved values, NOT the shipped file's 999s.
    assert loaded["north_x"] == 11.0
    assert loaded["south_x"] == 33.0
    assert loaded["selected"] == "north"


def test_load_map_layout_falls_through_when_no_qsettings_no_file(
    tmp_path: Path, _isolated_qsettings: Path
) -> None:
    """Empty QSettings AND no shipped map_layout.json (e.g. dev
    checkout that's never been calibrated, or an older release that
    predates this mechanism) ⇒ returns ``None`` so the caller
    falls back to the hard-coded vertical-stack default."""
    from cvfr_routemaster.settings_store import load_map_layout

    root = _make_release_tree(tmp_path, {})
    # No geo_calibration.json, no map_layout.json.

    assert load_map_layout(root) is None


def test_load_map_layout_backward_compatible_without_project_root(
    _isolated_qsettings: Path,
) -> None:
    """Calling :func:`load_map_layout` with no argument still works
    (matches the pre-fallback signature). Returns ``None`` when
    QSettings is empty, just like the old version, so any caller
    that hasn't been updated to thread ``project_root`` keeps
    behaving the same way."""
    from cvfr_routemaster.settings_store import load_map_layout

    assert load_map_layout() is None


def test_load_map_layout_ignores_corrupted_shipped_file(
    tmp_path: Path, _isolated_qsettings: Path
) -> None:
    """Corrupt / partial / wrong-type shipped file must NOT crash
    startup. Loader returns ``None`` (falls through to default)
    rather than letting a half-broken release brick first launch."""
    from cvfr_routemaster.settings_store import load_map_layout

    root = _make_release_tree(tmp_path, {})
    cache_dir = root / RELEASE_CACHE_SUBDIR
    # Invalid JSON.
    (cache_dir / "map_layout.json").write_text("{ not valid json", encoding="utf-8")
    assert load_map_layout(root) is None

    # Wrong top-level type (list instead of dict).
    (cache_dir / "map_layout.json").write_text("[1, 2, 3]", encoding="utf-8")
    assert load_map_layout(root) is None

    # Missing required field.
    (cache_dir / "map_layout.json").write_text(
        json.dumps({"north_x": 0.0}), encoding="utf-8"
    )
    assert load_map_layout(root) is None

    # Non-numeric value.
    (cache_dir / "map_layout.json").write_text(
        json.dumps(
            {
                "north_x": "oops",
                "north_y": 0.0,
                "north_scale": 1.0,
                "south_x": 0.0,
                "south_y": 0.0,
                "south_scale": 1.0,
            }
        ),
        encoding="utf-8",
    )
    assert load_map_layout(root) is None


# ---------------------------------------------------------------------------
# Regression: verbatim from the broken WSL build
# ---------------------------------------------------------------------------


def test_regression_verbatim_broken_wsl_build_geo_calibration(tmp_path: Path) -> None:
    """The actual stale fingerprints from the broken release-linux v2
    build. If this drifts, the bug-this-helper-was-built-for is back.

    Both north and south stored mtimes have sub-second tails matching
    NTFS 100-ns ticks (``...332421700``, ``...316700700``); both
    shipped PDFs have whole-second mtimes (``...000000000``) because
    WSL's 9P bridge floors them on copy.
    """
    from scripts._restamp_cache_fingerprints import (
        DEFAULT_NORTH_PDF,
        DEFAULT_SOUTH_PDF,
        restamp_cache_fingerprints,
    )

    NORTH_LIVE_NS = 1777797121_000_000_000
    SOUTH_LIVE_NS = 1777797137_000_000_000
    NORTH_STALE_NS = 1777797121_332_421_700
    SOUTH_STALE_NS = 1777797137_316_700_700

    root = _make_release_tree(
        tmp_path,
        {DEFAULT_NORTH_PDF: NORTH_LIVE_NS, DEFAULT_SOUTH_PDF: SOUTH_LIVE_NS},
    )
    _write_cache(
        root,
        "geo_calibration.json",
        {
            "version": 1,
            "north": {
                "pdf": {
                    "path": f"<repo-root>\\\\{DEFAULT_NORTH_PDF}",
                    "mtime_ns": NORTH_STALE_NS,
                    "size": 7910912,
                },
                "points": [],
                "map_layout": {"x": 0.0, "y": 0.0, "scale": 1.0},
            },
            "south": {
                "pdf": {
                    "path": f"<repo-root>\\\\{DEFAULT_SOUTH_PDF}",
                    "mtime_ns": SOUTH_STALE_NS,
                    "size": 8697353,
                },
                "points": [],
                "map_layout": {"x": 0.0, "y": 0.0, "scale": 1.0},
            },
        },
    )

    report = restamp_cache_fingerprints(root)
    assert report.total_fields_updated() == 2

    # Mtimes now match the live PDFs, so the next launch will hit
    # the calibration cache and the app will NOT show the modal
    # "please re-pick 8 anchor waypoints" dialog at startup —
    # which is the bug-symptom this whole helper exists to prevent.
    cached = _read_cache(root, "geo_calibration.json")
    assert cached["north"]["pdf"]["mtime_ns"] == NORTH_LIVE_NS
    assert cached["south"]["pdf"]["mtime_ns"] == SOUTH_LIVE_NS
