"""Re-stamp ``mtime_ns`` fields inside shipped cache JSONs to match
the live mtimes of the PDFs sitting next to them in the release tree.

Why
---

All four on-disk caches (``waypoints_cache.json``, ``geo_calibration.json``,
``altitude_arrows_{north,south}.json``, ``map_images_meta.json``) key
their validity check on the PDF's ``(mtime_ns, size)`` pair. Any drift
between the mtime stored at cache-write-time and the mtime the OS
reports when the app reads the shipped PDF at launch will invalidate
the cache and trigger a (slow, often impossible without extra system
deps) regeneration:

  * waypoints_cache.json → re-OCR (needs Tesseract installed; on the
    Linux release that means a ~150-MiB apt install the user might
    not have done yet).
  * geo_calibration.json → user is prompted to manually re-pick
    8 anchor waypoints on the chart, a several-minute ritual that
    requires the chart to already be readable; **disastrous UX**.
  * altitude_arrows_*.json → ~30-second off-thread re-extraction.
  * map_images_meta.json → re-render the chart PDFs to PNG, another
    ~30 seconds.

So every cache miss on first launch is between annoying and
showstopping. The release pipeline ships a fully-warm cache exactly
to avoid this.

The bug
-------

On a **Linux release built in WSL** (i.e. the developer's typical
workflow because PyInstaller can't cross-compile from Windows), the
build script copies the dev cache JSONs verbatim from
``.cvfr_routemaster/``. Those JSONs were generated by the app
running natively on Windows against the dev PDFs at the repo root —
with full NTFS-native sub-second mtime precision (NTFS stores 100-ns
ticks; the dev cache typically has ``mtime_ns = 1777797121332421700``
i.e. ``...121.332421700``).

The PDFs, in contrast, are copied **into** ``release-linux/map-pdfs/``
by ``shutil.copy2``, which on Linux reads the source mtime through
the kernel's view of ``/mnt/c/`` (the WSL 9P bridge). That bridge
**floors mtimes to whole seconds** — there's no way for the Linux
side to recover the sub-second tail of an NTFS mtime through ``/mnt/c``.
So the destination PDF lands with ``mtime_ns = 1777797121000000000``
(``...121.000000000``).

End state: shipped cache JSON says ``...121.332421700``; shipped PDF
says ``...121.000000000``. Equal-second but different-nanosecond.
The fingerprint check rejects, the cache invalidates, and the user
hits the regeneration cascade above on first launch.

The fix
-------

After ``_copy_charts()`` and ``_copy_seed_cache()`` have populated
the release tree, walk every cache JSON and overwrite each
``mtime_ns`` field with the live mtime of the PDF it references.
Idempotent (running it twice has no effect; the live mtime is
already what got written last time).

Used by:

  * ``scripts/build_release_for_linux.py`` — as a build step.
  * ``scripts/build_release.py`` — same (defensive; the Windows
    build happens to not hit this drift today because Windows-native
    Python preserves NTFS sub-second precision end-to-end, but
    keeping the step in both keeps the pipeline symmetric).
  * Ad-hoc fixup CLI: ``python3 -m scripts._restamp_cache_fingerprints
    <release-dir>`` to repair an already-shipped release on the
    target box without needing a full rebuild.

Cache JSON schemas
------------------

Four files, each with a slightly different shape:

  1. ``waypoints_cache.json``
       ``{"back_pdf": {"path": str, "mtime_ns": int, "size": int}, ...}``
       References: <release>/map-pdfs/CVFR-BACK-PAGES-*.pdf

  2. ``geo_calibration.json``
       ``{"north": {"pdf": {"path": str, "mtime_ns": int, "size": int}, ...},
          "south": {"pdf": {"path": str, "mtime_ns": int, "size": int}, ...}}``
       References: <release>/map-pdfs/CVFR-{NORTH,SOUTH}-*.pdf

  3. ``altitude_arrows_north.json`` / ``altitude_arrows_south.json``
       ``{"pdf": {"path": str, "mtime_ns": int, "size": int}, ...}``
       References: <release>/map-pdfs/CVFR-{NORTH,SOUTH}-*.pdf

  4. ``map_images_meta.json``
       ``{"north_pdf": {"path": ..., "mtime_ns": ...},
          "south_pdf": {"path": ..., "mtime_ns": ...}}``
       References: <release>/map-pdfs/CVFR-{NORTH,SOUTH}-*.pdf

The mapping from cache file → which PDF(s) drive its mtime is
captured in :data:`_CACHE_PDF_BINDINGS` so a future fifth cache or
PDF rename is a one-place edit.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path


# PDF filenames used by the release. Same constant ought to live in
# the build scripts; we duplicate here so this module is independently
# runnable as a CLI fixup tool without importing one of the build
# scripts (which carry heavier dependencies — PIL for icon generation,
# subprocess for PyInstaller invocation, etc.).
DEFAULT_NORTH_PDF = "CVFR-NORTH-OCT-2025-UPD2.pdf"
DEFAULT_SOUTH_PDF = "CVFR-SOUTH-OCT-2025-UPD2.pdf"
DEFAULT_BACK_PDF = "CVFR-BACK-PAGES-OCT-2025-UPD2.pdf"

# Standard subfolders inside a release root (Windows ``release/`` and
# Linux ``release-linux/`` use the same layout).
RELEASE_PDF_SUBDIR = "map-pdfs"
RELEASE_CACHE_SUBDIR = ".cvfr_routemaster"


@dataclass(frozen=True)
class _CacheBinding:
    """Maps one cache JSON to the PDF(s) whose mtime drives its
    ``mtime_ns`` fields.

    ``mtime_fields`` is a list of dotted JSON paths
    (e.g. ``["back_pdf"]`` or ``["north", "pdf"]``) — each path
    identifies a sub-dict where the ``mtime_ns`` key lives. ``pdf_name``
    is the corresponding PDF filename inside ``map-pdfs/`` for each
    field (same order as ``mtime_fields``).

    Using parallel lists rather than a dict-of-lists because the
    field order matters (we zip them) and because the dataclass
    documents the relationship more clearly than a bare tuple of
    tuples.
    """

    file_name: str
    mtime_paths: tuple[tuple[str, ...], ...]
    pdf_names: tuple[str, ...]


def _default_bindings() -> tuple[_CacheBinding, ...]:
    """The four cache files we ship and their PDF fingerprints.

    Function (not module-level constant) so callers can replace
    ``DEFAULT_*_PDF`` via overrides in tests / future chart-cycle
    transitions without monkey-patching the constants.
    """
    return (
        _CacheBinding(
            file_name="waypoints_cache.json",
            mtime_paths=(("back_pdf",),),
            pdf_names=(DEFAULT_BACK_PDF,),
        ),
        _CacheBinding(
            file_name="geo_calibration.json",
            mtime_paths=(("north", "pdf"), ("south", "pdf")),
            pdf_names=(DEFAULT_NORTH_PDF, DEFAULT_SOUTH_PDF),
        ),
        _CacheBinding(
            file_name="altitude_arrows_north.json",
            mtime_paths=(("pdf",),),
            pdf_names=(DEFAULT_NORTH_PDF,),
        ),
        _CacheBinding(
            file_name="altitude_arrows_south.json",
            mtime_paths=(("pdf",),),
            pdf_names=(DEFAULT_SOUTH_PDF,),
        ),
        _CacheBinding(
            file_name="map_images_meta.json",
            mtime_paths=(("north_pdf",), ("south_pdf",)),
            pdf_names=(DEFAULT_NORTH_PDF, DEFAULT_SOUTH_PDF),
        ),
    )


@dataclass(frozen=True)
class ShippedMapLayoutReport:
    """What ``write_shipped_map_layout`` did.

    Attributes:
      written: Path to the ``map_layout.json`` we wrote, or ``None``
        if nothing was written (see ``reason``).
      layout: The dict that was serialised (the same shape
        :func:`cvfr_routemaster.settings_store.load_map_layout`
        returns). ``None`` when no file was written.
      reason: ``None`` on success. Short tag otherwise:
        - ``"file_absent"``: ``geo_calibration.json`` not in the
          release cache dir, so there's no calibration to honour.
          The release will work fine via the in-app defaults.
        - ``"no_layouts"``: ``geo_calibration.json`` is present but
          neither sheet has a usable ``map_layout`` block. Same
          fall-through behaviour as ``file_absent``.
        - ``"meta_missing"``: needed ``map_images_meta.json`` (to
          compute the in-app default placement for an
          uncalibrated-but-still-shippable sheet) was absent. Build
          script treats this as a hard failure — see callers.
    """

    written: Path | None
    layout: dict | None
    reason: str | None


@dataclass(frozen=True)
class RestampReport:
    """What changed during a restamp pass.

    Attributes:
      updates: For each cache JSON, a list of
        ``(json_path_dotted, old_mtime_ns, new_mtime_ns)`` triples for
        the fields whose mtimes actually changed. Fields whose stored
        mtime already matched the live PDF mtime are not listed (the
        operation is idempotent — same call twice is a no-op the
        second time).
      skipped: Cache filenames that didn't exist in the cache
        directory. Optional caches (e.g. ``altitude_arrows_*.json``
        when the user only calibrated one sheet) are skipped silently
        rather than failing.
      missing_pdfs: PDF filenames referenced by a present cache but
        absent from ``map-pdfs/``. These would be a build-pipeline
        bug if seen on a completed build, so callers should print
        them as warnings.
    """

    updates: dict[str, list[tuple[str, int, int]]]
    skipped: list[str]
    missing_pdfs: list[str]

    def total_fields_updated(self) -> int:
        return sum(len(v) for v in self.updates.values())


def _walk_to_dict(root: dict, path: tuple[str, ...]) -> dict | None:
    """Descend a dotted JSON path. Returns the leaf dict, or None
    if any segment is missing or not a dict.

    Used to find the sub-object that owns ``mtime_ns`` without
    crashing on cache files written in a format we don't fully
    recognise — those get skipped quietly so a future schema bump in
    one cache doesn't break the whole build.
    """
    cur: object = root
    for seg in path:
        if not isinstance(cur, dict):
            return None
        cur = cur.get(seg)
    return cur if isinstance(cur, dict) else None


def restamp_cache_fingerprints(
    release_dir: Path,
    bindings: tuple[_CacheBinding, ...] | None = None,
) -> RestampReport:
    """Re-stamp PDF ``mtime_ns`` fields in every cache JSON under
    ``<release_dir>/.cvfr_routemaster/`` to match the live PDF
    mtimes under ``<release_dir>/map-pdfs/``.

    Idempotent. The cache JSON's ``size`` field is **not** touched —
    it's already correct (copying a file with ``shutil.copy2``
    preserves byte-for-byte content, so the size stored at cache-build
    time matches the shipped PDF). Only ``mtime_ns`` is the source of
    sub-second precision drift between Windows-native cache builds
    and WSL/9P file reads.

    Args:
        release_dir: The release root that contains both
            ``map-pdfs/`` and ``.cvfr_routemaster/`` subfolders
            (i.e. ``release/`` for the Windows build or
            ``release-linux/`` for the Linux build).
        bindings: Override the default cache→PDF mapping. Tests use
            this to exercise edge cases (synthetic cache layouts,
            unusual PDF filenames). Production callers pass ``None``.

    Returns:
        A :class:`RestampReport` describing what changed. Empty
        ``updates`` map plus empty ``skipped`` and ``missing_pdfs``
        lists is the steady-state "everything already matches" case.

    Raises:
        FileNotFoundError: if ``release_dir`` itself or its required
            subfolders are absent — that's a build-pipeline ordering
            bug (this step must run after ``_copy_charts`` +
            ``_copy_seed_cache``), and silently no-op'ing would mask
            the bug.
    """
    if not release_dir.is_dir():
        raise FileNotFoundError(
            f"Release directory does not exist: {release_dir}. "
            "_copy_charts and _copy_seed_cache must run before "
            "restamp_cache_fingerprints — see scripts/build_release_for_linux.py."
        )
    pdf_dir = release_dir / RELEASE_PDF_SUBDIR
    cache_dir = release_dir / RELEASE_CACHE_SUBDIR
    if not pdf_dir.is_dir():
        raise FileNotFoundError(
            f"PDF subdirectory missing: {pdf_dir}. "
            "_copy_charts() must run before this step."
        )
    if not cache_dir.is_dir():
        raise FileNotFoundError(
            f"Cache subdirectory missing: {cache_dir}. "
            "_copy_seed_cache() must run before this step."
        )

    if bindings is None:
        bindings = _default_bindings()

    updates: dict[str, list[tuple[str, int, int]]] = {}
    skipped: list[str] = []
    missing_pdfs: list[str] = []

    for binding in bindings:
        cache_path = cache_dir / binding.file_name
        if not cache_path.is_file():
            # The cache file is optional — the dev environment may
            # not have generated it yet (e.g. a fresh dev clone that
            # never ran altitude extraction). The build script's
            # _copy_seed_cache() already skips missing files with a
            # notice; we mirror that here.
            skipped.append(binding.file_name)
            continue

        with cache_path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)

        if not isinstance(data, dict):
            # Unrecognised top-level shape — be conservative and
            # skip rather than corrupt the file.
            skipped.append(binding.file_name)
            continue

        file_updates: list[tuple[str, int, int]] = []
        for json_path, pdf_name in zip(binding.mtime_paths, binding.pdf_names):
            live_pdf = pdf_dir / pdf_name
            if not live_pdf.is_file():
                # Build pipeline didn't copy the PDF this cache
                # references; record but don't crash — the parent
                # build script knows enough context to decide whether
                # this is a hard failure or a partial-build allowance.
                missing_pdfs.append(pdf_name)
                continue

            target = _walk_to_dict(data, json_path)
            if target is None:
                # Path doesn't exist in this JSON — schema may have
                # been bumped since the binding was defined.
                continue

            old_mtime = target.get("mtime_ns")
            if not isinstance(old_mtime, int):
                continue

            new_mtime = live_pdf.stat().st_mtime_ns
            if old_mtime == new_mtime:
                # Already matches — operation is idempotent.
                continue

            target["mtime_ns"] = new_mtime
            file_updates.append((".".join(json_path), old_mtime, new_mtime))

        if file_updates:
            # Write back only when something actually changed.
            # Preserve the original 2-space indentation that the app
            # uses elsewhere so a diff of the cache JSON before/after
            # restamp is the minimal expected delta (only mtime_ns
            # values change).
            with cache_path.open("w", encoding="utf-8") as fh:
                json.dump(data, fh, ensure_ascii=False, indent=2)
                fh.write("\n")
            updates[binding.file_name] = file_updates

    return RestampReport(
        updates=updates,
        skipped=skipped,
        missing_pdfs=missing_pdfs,
    )


SHIPPED_MAP_LAYOUT_FILE = "map_layout.json"


def _layout_from_calibration_block(block: object) -> tuple[float, float, float] | None:
    """Pull ``(x, y, scale)`` out of a single sheet's calibration
    block (the ``cal["north"]`` or ``cal["south"]`` dict inside
    ``geo_calibration.json``).

    Returns ``None`` if the block isn't a dict, doesn't have a
    ``map_layout`` sub-dict, or any of x/y/scale aren't numeric.
    Treating any of those as "no usable layout" lets the caller
    fall through to in-app defaults for that sheet without crashing
    on a half-populated calibration JSON.
    """
    if not isinstance(block, dict):
        return None
    ml = block.get("map_layout")
    if not isinstance(ml, dict):
        return None
    try:
        return float(ml["x"]), float(ml["y"]), float(ml["scale"])
    except (KeyError, TypeError, ValueError):
        return None


def write_shipped_map_layout(
    release_dir: Path, mode_id: str | None = None
) -> ShippedMapLayoutReport:
    """Derive ``release_dir/.cvfr_routemaster/map_layout.json`` from
    the layout encoded in ``geo_calibration.json``.

    When ``mode_id`` is given the calibration is read from — and the
    layout written into — the per-mode namespace
    (``.cvfr_routemaster/<mode_id>/``); otherwise the legacy flat
    ``.cvfr_routemaster/`` location is used. v4 releases ship each
    mode's seed under its own namespace, so the build invokes this
    once per mode.

    Why this exists
    ---------------

    The release ships a fully-warm calibration cache so a friend
    (or the VATSIM laptop) gets the chart geo-referenced on first
    launch without having to manually pick 8 anchor waypoints. Each
    sheet's calibration carries a ``map_layout`` block recording the
    on-screen pixmap position/scale that was active when the dev
    captured the anchor (u, v) data; on every app launch
    :func:`cvfr_routemaster.geo_calibration.load_sheet_calibration_or_reason`
    rejects the calibration if the **current** sheet position
    differs (the guard exists so any out-of-band sheet move —
    historically Alt+drag, now an Alt+wheel scale tick or a
    Reset Map Layout — invalidates the overlay rather than
    silently misaligning it).

    The trap: the current sheet position is loaded from
    :func:`cvfr_routemaster.settings_store.load_map_layout`, which
    reads QSettings (per-user registry on Windows,
    ``~/.config/CVFRRouteMaster/`` on Linux). **QSettings does not
    ship with the release tree.** So on a fresh machine,
    ``load_map_layout`` returns ``None`` and the sheets are placed
    at the hard-coded vertical-stack default — which almost never
    matches the dev's calibrated layout (sheets dragged
    side-by-side, south overlapping north slightly, etc.). The
    calibration is rejected and the modal "please re-calibrate"
    dialog fires.

    The fix: ship a release-side ``map_layout.json`` that
    ``load_map_layout`` consults as a second-priority fallback
    after QSettings. The file's content is **derived from the
    calibration itself** — whatever layout the dev calibrated
    against becomes the first-launch default. The user's own
    drag-arrangements on the release machine still win (they're
    saved to QSettings the first time the user moves a sheet), so
    this is a first-launch starting point, not an override the
    user has to keep dismissing.

    What gets written
    -----------------

    The output file is the same shape :func:`load_map_layout`
    returns — flat ``{north,south}_{x,y,scale}`` keys plus
    ``selected``. We derive each sheet's coordinates from the
    corresponding ``map_layout`` block inside
    ``geo_calibration.json``. If only one sheet is calibrated (the
    dev never got around to the other), the uncalibrated sheet
    falls back to the in-app default placement (north at (0, 0),
    south at (0, n_pixmap_height) — the same vertical-stack default
    the app would have applied with no layout loaded at all). The
    north pixmap height comes from ``map_images_meta.json``'s
    ``north_crop.cropped_h``.

    ``selected`` defaults to ``"south"`` (matches the in-app default
    inside :func:`load_map_layout`); calibration data doesn't record
    which sheet was "selected" because that's a UX preference, not
    a geo-referencing invariant.

    Returns:
        A :class:`ShippedMapLayoutReport`. ``reason`` is ``None``
        when a file was written; otherwise carries a short tag the
        build script uses to decide between "warn quietly" and
        "fail loudly".
    """
    cache_dir = release_dir / RELEASE_CACHE_SUBDIR
    if mode_id is not None:
        cache_dir = cache_dir / mode_id
    cal_path = cache_dir / "geo_calibration.json"
    meta_path = cache_dir / "map_images_meta.json"
    out_path = cache_dir / SHIPPED_MAP_LAYOUT_FILE

    if not cal_path.is_file():
        return ShippedMapLayoutReport(
            written=None, layout=None, reason="file_absent"
        )
    try:
        with cal_path.open("r", encoding="utf-8") as fh:
            cal = json.load(fh)
    except (OSError, json.JSONDecodeError):
        return ShippedMapLayoutReport(
            written=None, layout=None, reason="file_absent"
        )
    if not isinstance(cal, dict):
        return ShippedMapLayoutReport(
            written=None, layout=None, reason="file_absent"
        )

    north_layout = _layout_from_calibration_block(cal.get("north"))
    south_layout = _layout_from_calibration_block(cal.get("south"))

    if north_layout is None and south_layout is None:
        # geo_calibration.json exists but contains no usable layouts
        # (e.g. it was written by an older version, or has placeholder
        # blocks). Don't write a stub — the in-app default is fine.
        return ShippedMapLayoutReport(
            written=None, layout=None, reason="no_layouts"
        )

    # For sheets with no recorded layout, fill in the in-app default
    # placement so the shipped layout is complete. The app reads all
    # six positional fields unconditionally; emitting partial keys
    # would force the loader into "fall through to None" semantics
    # and the user would be told to re-calibrate even when only the
    # *uncalibrated* sheet was the problem.
    if north_layout is None:
        north_layout = (0.0, 0.0, 1.0)
    if south_layout is None:
        # Need north pixmap height for the default stack position.
        if not meta_path.is_file():
            return ShippedMapLayoutReport(
                written=None, layout=None, reason="meta_missing"
            )
        try:
            with meta_path.open("r", encoding="utf-8") as fh:
                meta = json.load(fh)
            n_pixmap_h = float(meta["north_crop"]["cropped_h"])
        except (OSError, json.JSONDecodeError, KeyError, TypeError, ValueError):
            return ShippedMapLayoutReport(
                written=None, layout=None, reason="meta_missing"
            )
        south_layout = (0.0, n_pixmap_h, 1.0)

    layout = {
        "north_x": north_layout[0],
        "north_y": north_layout[1],
        "north_scale": north_layout[2],
        "south_x": south_layout[0],
        "south_y": south_layout[1],
        "south_scale": south_layout[2],
        # The selected-sheet annotation isn't recorded in the
        # calibration; pick the same default the in-app loader uses
        # when nothing's saved (``"south"``) so the shipped file
        # round-trips cleanly through load_map_layout / save_map_layout.
        "selected": "south",
    }

    with out_path.open("w", encoding="utf-8") as fh:
        json.dump(layout, fh, ensure_ascii=False, indent=2)
        fh.write("\n")

    return ShippedMapLayoutReport(written=out_path, layout=layout, reason=None)


SHIPPED_FONT_SETTINGS_FILE = "font_settings.json"


@dataclass(frozen=True)
class ShippedFontSettingsReport:
    """What ``write_shipped_font_settings`` did.

    Attributes:
      written: Path to the ``font_settings.json`` we wrote, or
        ``None`` when no file was written (see ``reason``).
      sizes: The dict that was serialised. Includes any subset of
        ``{table_px, route_text_px, hint_px,
        airplane_table_px, airplane_route_text_px, airplane_hint_px,
        traffic_icon_size_px, waypoint_marker_size_px}`` the dev
        had explicitly set.
        ``None`` when no file was written.
      reason: ``None`` on success. Short tag otherwise:
        - ``"qsettings_empty"``: the dev's QSettings has none of
          the seven Display-Settings keys yet. The release will
          work fine via the hard-coded defaults.
    """

    written: Path | None
    sizes: dict | None
    reason: str | None


def write_shipped_font_settings(release_dir: Path) -> ShippedFontSettingsReport:
    """Snapshot the dev's current Font Settings preferences from
    QSettings and persist them as ``release_dir/.cvfr_routemaster/
    font_settings.json``.

    Why this exists
    ---------------

    Font Settings are stored in **QSettings** (the Windows registry
    on Windows, ``~/.config/CVFRRouteMaster/`` on Linux). QSettings
    is per-user and per-machine — it does not ship with the release
    tree, so a friend who unzips the release on a fresh machine
    gets QSettings = empty and the app falls back to the hard-coded
    defaults (12 / 12 / 18 px). That means the friend doesn't see
    the same UI the dev tested against (the dev may have bumped
    table fonts to 16 px for a hi-DPI monitor, for example).

    Mirrors the ``map_layout.json`` mechanism for calibration —
    both files exist to thread dev-side QSettings preferences
    across to a machine where QSettings is empty. The shipped
    settings are a *first-launch* default: the user's first
    interaction with the Font Settings dialog persists their own
    choice to QSettings on the receiving machine, and from then on
    QSettings wins on that machine.

    What gets written
    -----------------

    A small JSON dict that flattens the dev's whole Display-Settings
    snapshot into one document. Normal-mode font fields use the
    historical short names (``table_px`` / ``route_text_px`` /
    ``hint_px``) so older shipped files keep parsing. Airplane-mode
    fields use the ``airplane_*`` prefix, mirroring the
    ``airplane_font_*`` prefix QSettings uses internally. The
    traffic-icon size sits at the top level alongside the font
    fields under the same flat-key naming the QSettings store uses:

        {
          "table_px":                 <int>,
          "route_text_px":            <int>,
          "hint_px":                  <int>,
          "airplane_table_px":        <int>,
          "airplane_route_text_px":   <int>,
          "airplane_hint_px":         <int>,
          "traffic_icon_size_px":     <int>,
          "waypoint_marker_size_px":  <int>
        }

    Each "section" of fields is emitted independently:

      * The two font profiles each have all-or-nothing emission:
        if the dev has explicitly set at least one of the three
        keys for a profile, all three are written (with the
        profile's hard-coded defaults filling in any unset
        ones). If a profile has *no* explicit keys, none of its
        fields are emitted.
      * The traffic-icon size is a single key, emitted iff it has
        been explicitly set in QSettings.
      * The waypoint-marker size is the second single-key knob,
        emitted under its own flat key with the same explicit-only
        gating as the traffic-icon size.

    If *no* section has any explicit values the function returns a
    ``qsettings_empty`` report **without writing a file** — there's
    nothing to ship that wouldn't already be the in-app default,
    and emitting a redundant file would mask the case where the
    user genuinely wants the defaults from a future
    change-of-defaults that the shipped file overrides.
    """
    # Read directly through ``cvfr_routemaster.settings_store`` —
    # that module already centralises the org/app names and the
    # field-name conventions, so we don't risk drift between the
    # build script's "write to release" path and the app's
    # "read from QSettings" path. The build script imports the
    # package on the dev box where it's freely available; the
    # import doesn't need to succeed in a frozen release build
    # because this function is only ever called at build time.
    from cvfr_routemaster.settings_store import (  # noqa: PLC0415
        DEFAULT_AIRPLANE_HINT_FONT_PX,
        DEFAULT_AIRPLANE_ROUTE_TEXT_FONT_PX,
        DEFAULT_AIRPLANE_TABLE_FONT_PX,
        DEFAULT_HINT_FONT_PX,
        DEFAULT_ROUTE_TEXT_FONT_PX,
        DEFAULT_TABLE_FONT_PX,
        _settings,
    )

    s = _settings()
    # ``QSettings.contains`` lets us distinguish "explicitly saved
    # value" from "field absent, default returned" — important
    # because we want to write the shipped file only when the dev
    # has actually set a preference, not echo back the defaults.
    # Two key tuples, one per profile; the airplane tuple uses the
    # same ``json_key`` shape but with the ``airplane_`` prefix so
    # everything flattens into a single dict on output.
    normal_keys = (
        ("font_table_px", "table_px", DEFAULT_TABLE_FONT_PX),
        ("font_route_text_px", "route_text_px", DEFAULT_ROUTE_TEXT_FONT_PX),
        ("font_hint_px", "hint_px", DEFAULT_HINT_FONT_PX),
    )
    airplane_keys = (
        (
            "airplane_font_table_px",
            "airplane_table_px",
            DEFAULT_AIRPLANE_TABLE_FONT_PX,
        ),
        (
            "airplane_font_route_text_px",
            "airplane_route_text_px",
            DEFAULT_AIRPLANE_ROUTE_TEXT_FONT_PX,
        ),
        (
            "airplane_font_hint_px",
            "airplane_hint_px",
            DEFAULT_AIRPLANE_HINT_FONT_PX,
        ),
    )
    # Per-profile gating: we want to ship a profile *only* when the
    # dev has explicitly set at least one of that profile's keys in
    # QSettings. Otherwise we would freeze whatever the current
    # ``DEFAULT_AIRPLANE_*`` constants happen to be into the
    # release, which would override a future change-of-defaults on
    # friends' machines that copy this shipped file forward.
    def _profile_has_any_explicit(keys):
        return any(s.contains(qkey) for qkey, _, _ in keys)

    def _emit_profile_values(keys):
        # Within a profile, missing fields fall back to that
        # profile's defaults so the shipped JSON is always
        # fully-populated for any profile we emit at all — the
        # reader rejects half-populated profiles (returns ``None``)
        # to keep the "partial file = bug, fall through to
        # defaults" semantic clean.
        return {
            json_key: int(s.value(qkey, default, int))
            for qkey, json_key, default in keys
        }

    sizes = {}
    if _profile_has_any_explicit(normal_keys):
        sizes.update(_emit_profile_values(normal_keys))
    if _profile_has_any_explicit(airplane_keys):
        sizes.update(_emit_profile_values(airplane_keys))

    # Traffic-icon size — single key, emit iff explicitly set in
    # QSettings. We deliberately do NOT freeze the in-code default
    # into the shipped JSON when the dev never touched the setting,
    # because a future bump of ``DEFAULT_TRAFFIC_ICON_SIZE_PX``
    # should propagate to the friend's first launch on the next
    # release rather than being shadowed by a stale shipped value.
    # Same rationale as the per-profile gating above.
    if s.contains("traffic_icon_size_px"):
        # Defer the int() cast through QSettings.value's coercion
        # path so a corrupted entry surfaces here (at build time)
        # rather than at the friend's launch — easier to spot.
        sizes["traffic_icon_size_px"] = int(
            s.value("traffic_icon_size_px", 0, int)
        )

    # Waypoint-marker size — same explicit-only gating as the
    # traffic-icon size, same rationale (a future bump of
    # ``DEFAULT_WAYPOINT_MARKER_SIZE_PX`` should propagate to
    # friends' machines instead of being shadowed by a stale
    # shipped value the dev never deliberately committed to).
    if s.contains("waypoint_marker_size_px"):
        sizes["waypoint_marker_size_px"] = int(
            s.value("waypoint_marker_size_px", 0, int)
        )

    if not sizes:
        return ShippedFontSettingsReport(
            written=None, sizes=None, reason="qsettings_empty"
        )

    cache_dir = release_dir / RELEASE_CACHE_SUBDIR
    # The build script's ``_copy_seed_cache`` creates this dir, but
    # be defensive: if the caller invokes us in a fresh release
    # tree, ``mkdir(exist_ok=True)`` keeps the write atomic without
    # crashing on a pristine dir.
    cache_dir.mkdir(parents=True, exist_ok=True)
    out_path = cache_dir / SHIPPED_FONT_SETTINGS_FILE
    with out_path.open("w", encoding="utf-8") as fh:
        json.dump(sizes, fh, ensure_ascii=False, indent=2)
        fh.write("\n")

    return ShippedFontSettingsReport(written=out_path, sizes=sizes, reason=None)


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint for ad-hoc fixup of an already-shipped release.

    Usage::

        python3 -m scripts._restamp_cache_fingerprints <release-dir>

    Prints a per-file summary of what was updated, then exits
    non-zero if any PDF references couldn't be resolved (so a CI
    invocation can fail loudly on a half-built release).
    """
    parser = argparse.ArgumentParser(
        description="Re-stamp PDF mtimes in shipped cache JSONs so "
        "fingerprint checks hit on first launch.",
    )
    parser.add_argument(
        "release_dir",
        type=Path,
        help="Path to the release root (contains map-pdfs/ + .cvfr_routemaster/).",
    )
    args = parser.parse_args(argv)

    try:
        report = restamp_cache_fingerprints(args.release_dir)
        layout_report = write_shipped_map_layout(args.release_dir)
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    # Deliberately NOT calling ``write_shipped_font_settings`` here.
    # The CLI is an ad-hoc repair tool for an already-shipped
    # release — when a friend runs it on their target box, snapshot-
    # ing **their** (possibly empty / arbitrary) QSettings into the
    # release would actively damage the shipped state. Font-settings
    # snapshotting is a build-time concern only; ``scripts/build_release.py``
    # and ``scripts/build_release_for_linux.py`` call the writer
    # directly during release packaging.

    nothing_to_do = (
        not report.updates
        and not report.skipped
        and not report.missing_pdfs
        and layout_report.written is None
        and layout_report.reason in (None, "file_absent", "no_layouts")
    )
    if nothing_to_do:
        print("All cache JSON fingerprints already match; no calibration layout to ship.")
        return 0

    for cache_file, fields in report.updates.items():
        print(f"Updated {cache_file}:")
        for json_path, old, new in fields:
            print(f"  {json_path}.mtime_ns: {old} -> {new}")
    if report.skipped:
        print(f"Skipped (not present in cache dir): {', '.join(report.skipped)}")
    if layout_report.written is not None:
        print(f"Wrote shipped map layout: {layout_report.written.name}")
        for k, v in (layout_report.layout or {}).items():
            print(f"  {k} = {v}")
    elif layout_report.reason == "meta_missing":
        print(
            "ERROR: needed map_images_meta.json to compute default "
            "placement for an uncalibrated sheet, but it's absent.",
            file=sys.stderr,
        )
        return 1
    if report.missing_pdfs:
        print(
            f"WARNING: cache JSONs referenced PDFs that aren't in map-pdfs/: "
            f"{', '.join(sorted(set(report.missing_pdfs)))}",
            file=sys.stderr,
        )
        return 1
    if report.updates:
        print(f"Total mtime fields restamped: {report.total_fields_updated()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
